# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#facebook_app_id: 241488116286409
#facebook_app_secret: ec7f783178f46dece995fb616e97d91a
  
# Do not keep production secrets in the repository,
# instead read values from the environment.

development:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  facebook_key: <%= Figaro.env.facebook_key %>
  facebook_secret: <%= Figaro.env.facebook_secret %>
  twitter_app_id: <%= Figaro.env.twitter_app_id %>
  twitter_app_secret: <%= Figaro.env.twitter_app_secret %>
  google_oauth2_app_id: <%= Figaro.env.google_oauth2_app_id %>
  google_oauth2_app_secret: <%= Figaro.env.google_oauth2_app_secret %>
  s3_region: <%= Figaro.env.AWS_REGION %>
  bucket: <%= Figaro.env.S3_BUCKET_NAME %>
  s3_host_name: <%= Figaro.env.S3_HOST_NAME %>
  access_key_id: <%= Figaro.env.AWS_ACCESS_KEY_ID %>
  secret_access_key: <%= Figaro.env.AWS_SECRET_ACCESS_KEY %>
  NEW_RELIC_LICENSE_KEY: <%= Figaro.env.NEW_RELIC_LICENSE_KEY %>
  NEW_RELIC_LOG: <%= Figaro.env.NEW_RELIC_LOG %>
  PAPERTRAIL_API_TOKEN: <%= Figaro.env.PAPERTRAIL_API_TOKEN%>
  AIRBRAKE_API_KEY : <%= Figaro.env.AIRBRAKE_API_KEY  %>
  AIRBRAKE_PROJECT_ID: <%= Figaro.env.AIRBRAKE_PROJECT_ID %>
  REDIS_URL: <%= Figaro.env.REDIS_URL %>

test:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  facebook_key: <%= Figaro.env.facebook_key %>
  facebook_secret: <%= Figaro.env.facebook_secret %>
  twitter_app_id: <%= Figaro.env.twitter_app_id %>
  twitter_app_secret: <%= Figaro.env.twitter_app_secret %>
  google_oauth2_app_id: <%= Figaro.env.google_oauth2_app_id %>
  google_oauth2_app_secret: <%= Figaro.env.google_oauth2_app_secret %>
  s3_region: <%= Figaro.env.AWS_REGION %>
  bucket: <%= Figaro.env.S3_BUCKET_NAME %>
  s3_host_name: <%= Figaro.env.S3_HOST_NAME %>
  access_key_id: <%= Figaro.env.AWS_ACCESS_KEY_ID %>
  secret_access_key: <%= Figaro.env.AWS_SECRET_ACCESS_KEY %>
  NEW_RELIC_LICENSE_KEY: <%= Figaro.env.NEW_RELIC_LICENSE_KEY %>
  NEW_RELIC_LOG: <%= Figaro.env.NEW_RELIC_LOG%>
  PAPERTRAIL_API_TOKEN: <%= Figaro.env.PAPERTRAIL_API_TOKEN%>
  AIRBRAKE_API_KEY : <%= Figaro.env.AIRBRAKE_API_KEY  %>
  AIRBRAKE_PROJECT_ID: <%= Figaro.env.AIRBRAKE_PROJECT_ID %>
  REDIS_URL: <%= Figaro.env.REDIS_URL %>


production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  SENDGRID_USERNAME: <%= Figaro.env.SENDGRID_USERNAME %>
  SENDGRID_PASSWORD: <%= Figaro.env.SENDGRID_PASSWORD %>
  SENDGRID_API_KEY: <%= Figaro.env.SENDGRID_API_KEY %>
  SPARKPOST_API_KEY: <%= Figaro.env.SPARKPOST_API_KEY %>
  facebook_key: <%= Figaro.env.facebook_key %>
  facebook_secret: <%= Figaro.env.facebook_secret %>
  twitter_app_id: <%= Figaro.env.twitter_app_id %>
  twitter_app_secret: <%= Figaro.env.twitter_app_secret %>
  google_oauth2_app_id: <%= Figaro.env.google_oauth2_app_id %>
  google_oauth2_app_secret: <%= Figaro.env.google_oauth2_app_secret %>
  s3_region: <%= Figaro.env.AWS_REGION %>
  bucket: <%= Figaro.env.S3_BUCKET_NAME %>
  s3_host_name: <%= Figaro.env.S3_HOST_NAME %>
  access_key_id: <%= Figaro.env.AWS_ACCESS_KEY_ID %>
  secret_access_key: <%= Figaro.env.AWS_SECRET_ACCESS_KEY %>
  NEW_RELIC_LICENSE_KEY: <%= Figaro.env.NEW_RELIC_LICENSE_KEY %>
  NEW_RELIC_LOG: <%= Figaro.env.NEW_RELIC_LOG %>
  PAPERTRAIL_API_TOKEN: <%= Figaro.env.PAPERTRAIL_API_TOKEN %>
  AIRBRAKE_API_KEY : <%= Figaro.env.AIRBRAKE_API_KEY  %>
  AIRBRAKE_PROJECT_ID: <%= Figaro.env.AIRBRAKE_PROJECT_ID %>
  REDIS_URL: <%= Figaro.env.REDIS_URL %>


